Revising simulation script.

diff --git a/sim/proc_sim b/sim/proc_sim
--- a/sim/proc_sim
+++ b/sim/proc_sim
@@ -18,7 +18,14 @@ set -o nounset
 set -o pipefail
 IFS='$ \n\t'
 
-# Simulation script must be run from the /sim directory
+# Check usage and verify that a mode or test case was actually provided
+if [[ "$#" -eq 0 ]]; then
+    echo "Usage: proc_sim <mode or test case>"
+    exit 1
+fi
+
+# Verify that the simulation script is being run from the /sim directory
+# otherwise exit.
 full_pwd="$(readlink -f "$(pwd)")"
 if [[ "$(basename "$full_pwd")" == "sim" ]]; then
     root_dir="$(dirname "$full_pwd")"
@@ -27,7 +34,7 @@ else
     exit 1
 fi
 
-# Some commonly used directories
+# Set up commonly used variables and locations
 scripts_dir="$root_dir/scripts"
 build_dir="$root_dir/build"
 memory_ip="memory_block"
@@ -38,35 +45,49 @@ memory_model="blk_mem_gen_v8_3.v"
 tmp_dir="/tmp"
 sim_dir="$tmp_dir/proc_sim"
 
-# Make these environment variables  available to the Tcl interpreter
+# Export important variables so the EDA tools can be found
 export QUESTA_PATH="/opt/Altera/intelFPGA_pro/17.0/modelsim_ase/linux"
 export XILINX_VIVADO="/opt/Xilinx/Vivado/2017.1"
 
-# Supported addressing modes and test cases
-declare -a supported=("absolute"
-                      "absolute-x"
-                      "absolute-y")
+# Supported test ROMs or modes that can be run
+supported=("absolute")
+
+# Check available modes
+mode="${1:-}"
+found=false
+for available in "${supported[@]}"; do
+    if [[ "$mode" == "$available" ]]; then
+        echo "INFO: Running simulation for $mode addressing mode."
+        found=true
+        break
+    fi
+done
+
+# Exit if mode was not found to be one of the expected modes
+if ! "$found"; then
+    echo "ERROR: $mode is not a supported addressing mode."
+    exit 1
+fi
+
+# Establish a temp location to put the result of the simulation
+
+# Assemble the ROM into a .coe and .mif file
+
+# If it does not already exist, build a behavioral model for the Xilinx
+# block RAM
+
+# Move or copy all simulation files to the temp location
+
+# Run the requested simulation
+
+# Simulation script must be run from the /sim directory
+
+# Some commonly used directories
+
+
+# Make these environment variables  available to the Tcl interpreter
 
 # Error out if requested test case invalid or not provided
-if [[ "$#" -eq 0 ]]; then
-    echo "Usage: proc_sim <mode or test case>"
-    exit 1
-else
-    mode="${1:-}"
-    found=0
-    for available in "${supported[@]}"
-    do
-        if [[ "$mode" == "$available" ]]; then
-            echo "INFO: Simulating $mode addressing mode."
-            found=1
-            break
-        fi
-    done
-    if ((!found)); then
-        echo "ERROR: $mode is not a supported addressing mode or test case."
-        exit 1
-    fi
-fi
 
 # Delete any existing directory in /tmp - check to make sure that user has
 # permissions for this and error out if not (making different directories within
